name: "GenTx Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-gentx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: go version
      - name: Install dependencies
        run: sudo apt install -y boxes moreutils coreutils
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=changes::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- "./gentxs" | xargs)"
      - name: Check if added GenTx and if valid
        if: ${{ steps.changes.outputs.changes }}
        run: |
          bash -x ./scripts/validate-gentx.sh
        env:
          DAEMON: ./build/evmosd
          CHAIN_ID: evmos_9001-1
          DENOM: aevmos
          GH_URL: https://github.com/tharsis/evmos
          BINARY_VERSION: v1.0.0
          PROJECT_DIR: ${{ github.workspace }}
          GENTX_DIR: ./gentxs
          GENTX_FILE: ${{ github.workspace }}/${{ steps.changes.outputs.changes }}
